### ISSUE TITLE
Criação da página "Sobre"

### ISSUE THREAD

**Issue by vaporwavie** [RodolfoSilva/DeVryCalc#16]
## O que será feito
Em breve, uma página chamada **"Sobre"** será criada no intuito de mostrar mais sobre o projeto e quem são seus contribuidores. É importante ressaltar à galera interessada no DeVryCalc que seus nomes podem estar nesta página. O objetivo de criação desta é simplesmente mostrar quem está ajudando a tornar o funcionamento do app cada vez melhor! E não se esqueçam, este projeto é feito para todo mundo. :smile: 

## Mas Luiz, o que eu posso fazer para ter meu nome na página?
Acredite se quiser, mas você não precisa ser um **guru do código** para alimentar este repositório 😆. É possível ajudar com o desenvolvimento ao relatar bugs, sugerir melhorias **sem inserir sequer uma linha de código**. Além disso, você também pode compartilhar com todos os seus colegas de instituições da DeVry Brasil, pois ajuda a espalhar o conceito de todo o projeto. Já se você **for programador** e quer **MUITO** ajudar com bug fixes e afins, se liga nessas dicas:
* Busque aprendizado por JavaScript. Recomendo o [Eloquent JavaScript](http://eloquentjavascript.net)
* Queira conhecer o fundamento das duas frameworks que fizeram este app nascer, o [Ionic 2](https://ionicframework.com/docs/) e o [Angular 2](https://angular.io/). Não se preocupe, você provavelmente vai se enturmar facilmente com o conceito das duas, e vai mantê-las contigo por um bom tempo, *acredite*.
* Adquira uma noção em CSS. Neste aplicativo em especifico, além do TypeScript (variação para o JavaScript fortemente tipada), utilizamos SASS, que, como sua sigla diz (sim, é uma sigla), ela é uma **Folha de Estilos Sintaticamente Foda (Syntactically Awesome Style Sheets)**
* **<h2>Pergunte! (e isso é muito importante.)</h2>** No momento, eu (@vaporwavie) e Rodolfo - que começou e mantém o projeto (@RodolfoSilva) - estamos movimentando o app. Você pode nos perguntar sempre que precisar. Insista no uso dessa guia (**Issues**) para questionar quaisquer situações presenciadas pela aplicação. Sério, nós vamos te responder de boa e não vamos te chamar de chato (a) :rofl:
* Se você **nunca** utilizou esta ferramenta que vos comunico, o Github, insisto que tirem um tempo para explorá-la. Também peço que conheçam (e aprendam) o significado e o poderoso uso do Git, que, acredite, é muito foda. 

Então é isso! Desejo a todos um ótimo proveito deste projeto que, sério, tá sendo muito divertido contribuir e saber que as pessoas estão gostando/utilizando. Assim sendo, contamos com o apoio de futuros contribuidores! 😃

**Comment by RodolfoSilva** [comment]
Movido para a wiki: [**Quero contribuir**](https://github.com/RodolfoSilva/DeVryCalc/wiki/Quero-contribuir)
