### ISSUE TITLE
Disciplina armazenada sem nome se torna "Undefined"

### ISSUE THREAD

**Issue by vaporwavie** [RodolfoSilva/DeVryCalc#2]
No menu de criação da disciplina, o nome pode ser salvo em branco, retornando Undefined. Não deveria haver um <code>required</code> pro input do nome da disicplina? 

### Prévia

![preview](http://i.imgur.com/Buqcwxi.png)

**Comment by RodolfoSilva** [comment]
Sim @vaporwavie acabei de adicionar isso nesse PR #4. 
Obrigado :smile:

**Comment by RodolfoSilva** [comment]
Done #4
