### ISSUE TITLE
Pacote quebrado do NPM impedindo funcionamento local

### ISSUE THREAD

**Issue by vaporwavie** [RodolfoSilva/DeVryCalc#40]
Achei que o erro era só com minha máquina, até que percebi que o Travis também não consegue realizar os testes em qualquer PR. É um erro bizarro que rola quando o <code>npm i</code> é executado... Tem um dos pacotes que usamos no projeto que ou tá com o link quebrado ou não funciona mais... Precisamos dar uma olhada nisso ASAP

**Comment by RodolfoSilva** [comment]
@vaporwavie obrigado pelo report man. Mas esse bug vai deixar de fazer sentido. Migrei a stack para react.
