### ISSUE TITLE
Fazer previsão de notas

### ISSUE THREAD

**Issue by RodolfoSilva** [RodolfoSilva/DeVryCalc#6]
Fazer uma previsão para as notas AP1 e AP2 quando o aluno tenha cadastrado a AP3 e ainda tenha que fazer as provas substitutivas da AP1 ou da AP2, devemos mostrar para este aluno qual seria a nota minima que ele deve tirar para passar.

**Comment by RodolfoSilva** [comment]
Após uma curta discussão no grupo dos alunos de TI da Ruy sobre a formulá de calculo da nota da AP3, o colega **Leandro Moraes** expandiu a expressão utilizando uma incógnita.

![image](https://cloud.githubusercontent.com/assets/1703020/22856323/d0c9ffb0-f06d-11e6-9afe-0622b6e87228.png)

O que nos levou a uma simples expressão para determinar qual seria a nota necessária a ser tirada na AP1 ou na AP2.
![image](https://cloud.githubusercontent.com/assets/1703020/22856325/d8ca7726-f06d-11e6-8fc4-6d56cf05dd7b.png)

Ficando algo como:

```python
lambda ap3, apx: (50 - (apx * 3 + ap3 * 4)) / 3
```

**Comment by vaporwavie** [comment]
Bala! Agora o app poderá cobrir qualquer condição, após implementado :smile:

**Comment by RodolfoSilva** [comment]
:D
