### ISSUE TITLE
Bug ao excluir todas as materias

### ISSUE THREAD

**Issue by luizsantos1997** [RodolfoSilva/DeVryCalc#8]
Mesmo após excluir todas as matérias e programa continua mostrando a última matéria excluída na tela e ao adicionar outra matéria ela sobrescreve .

**Comment by vaporwavie** [comment]
### Referência para o bug
![bug](http://i.imgur.com/eeUv2T7.png)
@RodolfoSilva

**Comment by RodolfoSilva** [comment]
Já estou trabalhando nela :D

**Comment by RodolfoSilva** [comment]
O problema vai ser resolvido pelo **PR** #17.

Mas somente para contextualizar e explicar o que estava acontecendo:

Eu acabei me esquecendo de passar um atributo no botão e não conseguia ter o mesmo comportamento na minha maquina. Mas explicando mais profundamente segundo a documentação da [W3C](https://www.w3.org) o botão ou [button](https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html) quando definido sem um tipo por padrão o seu tipo é o **submit**. Logo como o botão estava dentro do formulário, ele estava executando a ação de excluir a disciplina e ao mesmo tempo enviando o formulário para cadastrar a disciplina.

Mais detalhes sobre o elemento [**button**](https://www.w3.org/wiki/HTML/Elements/button).

**Comment by RodolfoSilva** [comment]
Obrigado @luizsantos1997 e @vaporwavie pelo report :smile:
