### ISSUE TITLE
Não da pra adicionar uma nota com valor quebrado

### ISSUE THREAD

**Issue by luizsantos1997** [RodolfoSilva/DeVryCalc#9]
O teclado não mostra "." para colocar um valor quebrado

**Comment by RodolfoSilva** [comment]
Estamos utilizando o formato numérico nos campos de nota, isso funciona em boa parte das versões android:
![image](https://cloud.githubusercontent.com/assets/1703020/22856237/7506d0a0-f06c-11e6-8175-183de8f13879.png)

Porém na versão 4.4.2 do android da LG em especifico o LG-D2 o teclado é diferente:
![image](https://cloud.githubusercontent.com/assets/1703020/22856245/9454e974-f06c-11e6-8e92-008283ab1d76.png)

Utilizando o teclado para números de telefone ele disponibiliza a opção de inserir o ponto.
![image](https://cloud.githubusercontent.com/assets/1703020/22856216/32d3e042-f06c-11e6-97e3-b875b297e8c7.png)

A possivel solução para este problema é utilizar o teclado de telefone para qualquer dispositivo ou verificar se trata-se de um dispositivo usando Android 4.4 e então optar por utilizar o campo de telefone no lugar do numerico.

**Comment by vaporwavie** [comment]
@RodolfoSilva mudando a tag passando o tipo pra <code>tel</code> já resolveria? Ou seriam necessárias mais implementações?

**Comment by RodolfoSilva** [comment]
@vaporwavie resolveria sim

**Comment by vaporwavie** [comment]
Beleza!
